version: 2
jobs:
  build:
    working_directory: /go/src/github.com/boundlessgeo/gometry
    docker:
      - image: circleci/golang:1.10
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go test -v ./...
